### ISSUE TITLE
Allow dashmate role to build from sources or use versions

### ISSUE THREAD

**Issue by pshenmic** [dashpay/dash-network-deploy#477]
## Expected Behavior

Deploy tool should be able to choose whether we want to build the whole platform branch, or use tagged versions to deploy dashmate on the nodes. 

During development, it is often necessary to specify platform_branch and build all of the dashmate services to keep up infrastructure with the code.

## Current Behavior

You can choose platform branch for dashmate, but you only can deploy tagged docker versions

## Possible Solution

Implement 3 modes in the dashmate role:
* Deploy everything from tagged images (use dashmate from npm, and set docker images)
* Build and run dashmate from `platform_branch`, but still use tagged images for services deployment
* Build every dashmate service from `platform_branch` and then start the node

**Comment by shumkov** [comment]
It's done https://github.com/dashpay/dash-network-deploy/pull/479
