### ISSUE TITLE
Remove mn_evo_services role from seed nodes

### ISSUE THREAD

**Issue by pshenmic** [dashpay/dash-network-deploy#514]
## Expected Behavior

Seed nodes should only run core tenderdash and seed containers, without dapi, envoy and the rest of the stuff

## Current Behavior

Legacy mn_evo_services role is used to deploy all platform services on the host

**Comment by shumkov** [comment]
Actually we need dashd there, but we don't need mn_evo_services except Tenderdash

**Comment by pshenmic** [comment]
Sorry guys, I think I messed up dashd with mn_evo_services role in the beginning and confused you

**Comment by pshenmic** [comment]
https://github.com/dashpay/dash-network-deploy/pull/535
