### ISSUE TITLE
DAPI smoke tests are not working on seeds

### ISSUE THREAD

**Issue by pshenmic** [dashpay/dash-network-deploy#554]
## Expected Behavior

DAPI smoke tests should be working on the seed nodes

## Current Behavior

They are not working, because because tenderdash is being run in `seed` mode, which disables Tenderdash RPC endpoint. Thus, dashmate is not able to gather necessary information for a proper smoke test execution

## Possible Solution
Look into tenderdash prometheus data if there is all necessary data for this task

**Comment by strophy** [comment]
Resolved in https://github.com/dashpay/dash-network-deploy/pull/565

DAPI no longer runs on seed nodes. Tenderdash on seed nodes is tested like this: https://github.com/dashpay/dash-network-deploy/blob/v0.25-dev/test/smoke/tenderdash.js#L172
